# yaml-language-server: $schema=https://schemas.lbrunner.net/home-assistant/addon-config.schema.json
name: "AT Protocol PDS"
description: "Self-hosted AT Protocol Personal Data Server for Bluesky and the Atmosphere"
version: "0.0.3"
slug: "atproto-pds"
url: "https://github.com/LouisBrunner/ha-addons/blob/main/atproto-pds"
image: ghcr.io/louisbrunner/ha-atproto-pds
init: false
arch:
  - aarch64
  - amd64
options:
  hostname: ""
  admin_password: ""
  smtp_url: ""
  invite_required: true
  gatekeeper:
    enabled: true
    captcha:
      enabled: false
    only_migrations: false
  customize:
    enabled: false
    caddyfile_filename: pds.caddyfile
  debug: false
schema:
  hostname: str
  admin_password: password
  smtp_url: password
  smtp_from: str?
  invite_required: bool?
  recovery_did_key: str?
  gatekeeper:
    enabled: bool?
    captcha:
      enabled: bool?
      hcaptcha_site_key: str?
      hcaptcha_secret_key: password?
    only_migrations: bool?
  customize:
    enabled: bool?
    caddyfile_filename: str?
  debug: bool?
ports:
  3000/tcp: null
map:
  - share
