# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Builder

env:
  MONITORED_FILES: "config.yaml Dockerfile rootfs server run.sh"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  init:
    name: Initialize builds
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.filter.outputs.changed }}
      changed_addons: ${{ steps.filter.outputs.changed_addons }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Get changed files
        id: changed_files
        uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # v47

      - name: Find add-on directories
        id: addons
        uses: home-assistant/actions/helpers/find-addons@f4ca6f671bd429efb108c0f2fa0ae8af0215986c

      - name: Filter changed add-ons
        id: filter
        env:
          ADDONS: ${{ steps.addons.outputs.addons }}
          CHANGED_FILES: ${{ steps.changed_files.outputs.all_changed_files }}
        run: |
          changed_addons=()

          if [[ "${CHANGED_FILES}" =~ \.github/workflows/(builder|build-addon)\.yaml ]]; then
            read -ra changed_addons <<< "${ADDONS}"
          else
            for addon in ${ADDONS}; do
              for file in ${MONITORED_FILES}; do
                if [[ "${CHANGED_FILES}" =~ ${addon}/${file} ]]; then
                  changed_addons+=("${addon}")
                  break
                fi
              done
            done
          fi

          if [[ ${#changed_addons[@]} -gt 0 ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
            echo "changed_addons=$(jq -nc '$ARGS.positional' --args "${changed_addons[@]}")" >> "$GITHUB_OUTPUT"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi

  build-addon:
    name: Build ${{ matrix.addon }}
    needs: init
    if: needs.init.outputs.changed == 'true'
    permissions:
      contents: read
      id-token: write
      packages: write
    strategy:
      fail-fast: false
      matrix:
        addon: ${{ fromJSON(needs.init.outputs.changed_addons) }}
    uses: ./.github/workflows/build-addon.yaml
    with:
      addon: ${{ matrix.addon }}
      publish: ${{ github.event_name == 'push' }}
