name: Lint

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  find:
    name: Find add-ons
    runs-on: ubuntu-24.04
    outputs:
      addons: ${{ steps.addons.outputs.addons_list }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - id: addons
        uses: home-assistant/actions/helpers/find-addons@f4ca6f671bd429efb108c0f2fa0ae8af0215986c

  lint:
    name: Lint add-on ${{ matrix.path }}
    runs-on: ubuntu-24.04
    needs: find
    strategy:
      matrix:
        path: ${{ fromJson(needs.find.outputs.addons) }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: frenck/action-addon-linter@v2.21
        with:
          path: "./${{ matrix.path }}"
